### ISSUE TITLE
add_surv_prob/add_hazard doesn't work without original data

### ISSUE THREAD

**Issue by iMSQ** [adibender/pammtools#203]
I created ped dataset:
`ped <- origData %>% as_ped(Surv(fgtime, fgstatus) ~ ., id = "id",  cut = seq(0, 10, by = 1))`
Then I fitted model:
`pam <- mgcv::gam(ped_status ~ s(tend) + "other covariates",  data = ped, family = poisson(), offset = offset)`

I have to remove the original data from the fitted model (to upload it on server):
`pam$model <- NULL`

But now I can't compute the hazard/survival probability for new data:
```
ped_newdf <- newData %>% as_ped(Surv(tend, status) ~ ., cut = seq(0, 10, by = 1))
ped_newdf <- make_newdata(ped_newdf, tend = unique(tend)) %>% add_hazard(pam, overwrite=TRUE)

_**Error in is.data.frame(data) : object 'ped' not found**_
```

- Is it possible to add hazard/survival probability without using of original data in fitted model?
- Is there another way to remove original data from fitted model?
 
Thank you.

**Comment by adibender** [comment]
Hi, thanks for reporting. 
The error occurs because internally the function checks, whether the intervals/cut points used in the original fit are the same as in new data set. Which cannot be done when you remove the original data set. 
I have now updated the function such that it doesn't make that check if the original data is not provided. 
Alternatively, you could use the `pamm` function to fit the model. The resulting object is essentially equivalent to the mgcv model output, but also stores the intervals used to fit the model. Therefore you could remove the original data and the checks will still be performed. 

Currently the new version is only on GitHub, so you'd have to install via `devtools::install_github("adibender/pammtools")`, however, I plan to submit the updated version to CRAN soon.
