### ISSUE TITLE
problem  x is empy

### ISSUE THREAD

**Issue by marcoguerzoni** [adibender/pammtools#214]
I am not able to replicate this code. I tried with older version of purrr and  also to run it on https://rdrr.io/snippets/.

```
library(dplyr); library(tidyr); library(purrr); library(ggplot2)
library(survival); library(mgcv); library(pammtools)

data("pbc", package="survival")
# event time information
pbc <- pbc %>%
  filter(id <= 312) %>%
  mutate(status = ifelse(status==0,0,1) )%>%
  select(id:status, trt:sex, bili, protime)
pbc %>% slice(1:6)


pbc_ped <- as_ped(
  data = list(pbc, pbcseq),
  formula = Surv(pbc$time, pbc$status)~sex|concurrent(bili, protime, tz_var = "day"),
  id = "id")
```

It return the error:

> Error: .x is empty, and no .init supplied

Thank you for any help!

**Comment by dwinsemius** [comment]
Three problems: 
1) using `$` in Surv arguments. It screws up handling varianble names in environments. Formula carry references to their environments and generally need a data argument. Using `$` screws up the references. 
2) no definition of pbc_seq. 
3) Using "|" rather than "+"

Marco can be excused for that last one since that error is in the documentation, which could easily be fixed.

**Comment by marcoguerzoni** [comment]
thanks, the problem is the use of | instead of + -  have a nice day.

**Comment by adibender** [comment]
Thnx @dwinsemius, I didn't notice the `|`. 
If everything is working now @marcoguerzoni , please close the issue
