### ISSUE TITLE
Issue with as_ped(), with left-truncated data and custom cut points.

### ISSUE THREAD

**Issue by AngelaCar** [adibender/pammtools#237]
Hello! I have stumbled on an issue using the as_ped function to prepare some left-truncated data.
It seems that when using the start-stop format and with specifying custom intervals using cut = ... the functions produces incorrect results. 

In my understanding, with default options, the function creates a cut point at each entry time. However, if I want to have custom cut intervals, that are larger than those of the default options, the function returns incorrect results.

Here is a reproducible example using the same example in the vignette:

```
library(pammtools)

data(infants, package = "eha")
infants_ped <- infants %>% as_ped(Surv(enter, exit, event)~.)

infants_ped_wrong <- infants %>% as_ped(Surv(enter, exit, event)~., cut = c(100,200,300,365))
```

Ideally, I would like to have these intervals: (0 - 100], (100-200], (200-300], (300-365].
The left-truncated observations should then be placed in the right interval, and their offset accounting for the fact that they enter later than the interval's left boundary.
For example, subject 1 should enter in the interval [0 - 100), but only contribute for 45 days instead of the 100 days.

Here is a screenshot of the results:
![image](https://github.com/adibender/pammtools/assets/56386685/2e00c5c9-a1be-40c5-8d81-1b3a4010919d)

Am I using the function wrongly?

Thank you!
Angela

**Comment by adibender** [comment]
Hello, 
I thought about it when implementing left-truncation, but decided to always do split points at each entry time, because I didn't want to estimate the hazard for say interval (0,100] based on many/any subjects that are not at risk yet. 
While similar arguments could be made for right censoring and events, i.e. not all subjects will be at risk for the whole interval, they are at least at risk at the beginning of the interval and we account for their time at risk via the offset in the likelihood. 
With your suggestion, there seem to be some problems. Say we have subject entering at 50 and right-censored at 70. 
We include them in interval (0, 100] with offset log(20), but then that the same as a subject that's at risk from 0 and censored at 20. 

However, I haven't thought about it too much, so if there is some literature/math/experiments that show that it's OK to treat left-truncated subjects equally to right-censored ones, I'm happy to adjust the function.

**Comment by adibender** [comment]
@AngelaCar I'll close for now, please reopen as needed
