### ISSUE TITLE
consolidate transformation functions

### ISSUE THREAD

**Issue by adibender** [adibender/pammtools#39]
Currently, vignettes, examples etc. use different functions to create PED data

- [x] Extend `as_ped` to be able to create PED data with concurrent TDCs, currently implemented in `split_tdc` (see https://adibender.github.io/pammtools/articles/tdcovar.html#analysis-of-the-pbc-data). Could be implemented by introducing a new special `concurrent`, i.e. 
```r
list(pbc, pbcseq) %>% as_ped(Surv(time, status)~.|concurrent(bili, protime,  te_var = "day"), ...)
```

- [x] Adjust all examples
- [x] Adjust vignettes

- [x] in `as_ped`, need better handling of `cut` if unspecified. Currently cut selected for TDC data not the same as the one selected by `split_data`

~~-[ ] maybe have `as_ped` return nested dfs by default? -> better printing, etc.~~
- [x] rename `func` to `cumulative`

**Comment by fabian-s** [comment]
- definitely would be nice to have `as_ped` deal with concurrent TDCs as well, in a similar fashion as `func` for cumulative effects, I like the idea in your first point above
- renaming  `func` to `cumulative` would make that distinction more obvious/easier to remember...?
- `nested_df` as default don't make sense to me -- modeling functions can't deal with them and this is prepocessing in order to fit a model.
